
FROM alpine:3.18

WORKDIR /workdir

# Alpine 3.18 has gfortran 12.  3.19 has gfortran 13 which didn't work with
# syntran until syntran 0.0.61, released 2025 Feb 1
RUN apk add --no-cache \
	gfortran \
	musl-dev \
	libc6-compat \
	rlwrap \
	curl
# - libc6-compat:  syntran needs glibc compatibility, not alpine's musl libc
# - rlwrap:  nice to have

# Beware, this does not run gen-header.sh like rocky docker. Maybe that's
# actually a good test that I have the generated source existing locally
COPY src src
COPY CMakeLists.txt .
COPY fpm.toml .

#************
## Build the fortran build system fpm from source.  Takes 3+ minutes
#RUN apk add git
#RUN git clone https://github.com/jeffirwin/fpm /fpm
#RUN cd /fpm && ./install.sh --prefix="/usr/"
#
## Build syntran
#RUN fpm install --prefix="/usr/"
#************

# Install fpm from binary
RUN curl -LO https://github.com/fortran-lang/fpm/releases/download/current/fpm-linux-x86_64
RUN mv fpm-linux-x86_64 fpm
RUN chmod +x fpm
RUN mv fpm /usr/local/bin
RUN fpm --version

RUN fpm install --prefix="/usr/"
RUN fpm test test

##************
## Takes 30 seconds
#RUN apk add cmake make
##RUN ./build.sh  # no bash on alpine :(
#
#RUN cmake -S . -B "build" -DCMAKE_BUILD_TYPE=Debug
#RUN cmake --build "build" --config Debug
##RUN cmake -S . -B "build" -DCMAKE_BUILD_TYPE=Release
##RUN cmake --build "build" --config Release
#
#RUN ./build/Release/test
#
#RUN cp ./build/Release/syntran /usr/bin/
##************

ENTRYPOINT ["rlwrap", "syntran"]

#===========================================================
# Tests
#
# This container is kinda bulky.  Maybe I should move tests to a separate
# dockerfile (debug build only?) for efficiency

RUN [[ "$(syntran -c '1+2;' | tr -d '[:space:]')" == "3" ]]
RUN [[ "$(syntran -c 'sum([0:101]);' | tr -d '[:space:]')" == "5050" ]]
RUN [[ "$(syntran -c 'sum([0:10]**2);' | tr -d '[:space:]')" == "285" ]]

RUN [[ "$(syntran -c 'let a = std::args(); size(a);' -- foo bar hello world | tr -d '[:space:]')" == "4" ]]
RUN [[ "$(syntran -c 'let a = std::args(); size(a);' -- foo bar 'hello world' | tr -d '[:space:]')" == "3" ]]

# `tr` deletes all spaces, while this `sed` only removes *leading* spaces
RUN [[ "$(syntran -c 'let a = std::args(); a[0];' -- foo bar 'hello world' | sed 's/^[[:space:]]*//')" == "foo" ]]
RUN [[ "$(syntran -c 'let a = std::args(); a[2];' -- foo bar 'hello world' | sed 's/^[[:space:]]*//')" == "hello world" ]]

