
# Tested with fpm 0.9.0
#
# Drive fpm with commands like this:
#
#     fpm clean --all
#     fpm build
#     fpm run # TODO: it doesn't use rlwrap. probably some way to configure
#     fpm test
#     fpm install --prefix ~
#
# fpm is smart.  If you run `fpm install` or `fpm test` without building first,
# it will automatically build
#
# Binary installers for fpm are available, but I built it from source:
#
#     git clone https://github.com/fortran-lang/fpm
#     cd fpm/
#     ./install.sh -h
#     ./install.sh --prefix='$HOME'
#     which fpm
#     ls ~/bin/
#     fpm --version

name = "syntran"
#version = "0.0.27"
license = "LICENSE"
author = "Jeff Irwin"
#maintainer = "jane.doe@example.com"
#copyright = "Copyright 2021, Jane Doe"
description = "syntran is an array-oriented language with an interpreter written in Fortran"
categories = ["interpreter"]
homepage = "https://github.com/JeffIrwin/syntran"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name = "syntran"
source-dir = "src"
main = "main.f90"

[[test]]
name = "test"
source-dir = "src/tests/"
main = "test.f90"

