fn quine(s: str) {
    let lparen    = char(40);
    let rparen    = char(41);
    let quote     = char(34);
    let semicolon = char(59);
    println(
        s + lparen + quote +
        s + quote + rparen + semicolon
    );
    return;
}
quine("fn quine(s: str) {
    let lparen    = char(40);
    let rparen    = char(41);
    let quote     = char(34);
    let semicolon = char(59);
    println(
        s + lparen + quote +
        s + quote + rparen + semicolon
    );
    return;
}
quine");
