
FROM ubuntu:latest

WORKDIR /workdir

COPY artifact-download ./artifact-download

RUN mv artifact-download/* /usr/local/bin
RUN chmod +x /usr/local/bin/syntran

# Set LD_LIBRARY_PATH for dependent libs
RUN echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/bin" >> ~/.bashrc

RUN source ~/.bashrc && syntran --version
RUN source ~/.bashrc && syntran --version --color on
RUN source ~/.bashrc && syntran -c 'println("hello world");'

