
! BEGIN INTERNAL
!
! Runtime support for Fortran programs generated by `syntran --transpile`.
!
! This file is embedded at the top of every transpiled program, so it must be
! a self-contained, standard-conforming Fortran module with no dependencies
! other than the Fortran standard library.  Use *spaces* for indentation here,
! unlike the rest of the syntran sources: a tab character is nonstandard in
! free-form Fortran and gfortran warns about it in user programs.
!
! It is also compiled into the syntran library itself, so the compiler checks
! it on every normal build and the unit tests can call it directly.
!
! After editing, regenerate src/transpile_rt.f90 with src/gen_transpile_rt.sh.
! Keep lines under 100 characters.
!
! This block, from BEGIN INTERNAL to END INTERNAL, is for syntran developers,
! so gen_transpile_rt.sh leaves it out of what is embedded.  End users see the
! comment inside the module instead, so keep that one short and free of
! anything about the syntran sources.
!
! Naming: every public name starts with `rt_`.  A name from a syntran program
! that starts the same way gets a `u` in front of it by the transpiler (see
! avoid_runtime_prefix() in transpile_expr.f90), so there are no clashes.  The
! exception is what this module re-exports from iso_fortran_env, which the
! transpiler doesn't let a program's names have either (see reserved_name()).
!
! Layout: a generated program only gets the procedures that it uses, which
! split_units() in transpile.f90 finds by the layout of this file, and
! transpile_rt_units_ok() checks.  So
!
!   - the module's one `contains` is at column 1, before the first procedure
!   - a procedure starts at column 1 with `function` or `subroutine`, possibly
!     after `pure`, `elemental` or `recursive`, so its type is declared in its
!     body, and ends with `end function` or `end subroutine` at column 1.  Its
!     internal procedures are indented
!   - a generic `interface` is indented by 4 spaces, in the module's
!     declarations.  The comment lines right above it come with it
!   - the comment lines above a procedure come with it too, up to the end of
!     the previous procedure
!
! END INTERNAL

!===============================================================================

module syntran_rt

    ! Runtime support for Fortran programs generated by `syntran --transpile`:
    ! printing numbers and arrays the way syntran does, ranges, strings, file
    ! I/O, and so on.  It uses only standard Fortran

    use, intrinsic :: iso_fortran_env, only: int32, int64, real32, real64, output_unit, &
        error_unit, input_unit, iostat_end, iostat_eor
    implicit none

    ! Arrays of strings are arrays of this, because Fortran has no array of
    ! varying-length strings
    type :: rt_str_t
        character(len = :), allocatable :: s
    end type rt_str_t

    ! A file handle.  Like the interpreter's, it is a value: reading from it
    ! updates the variable that it was read through, not other copies
    type :: rt_file_t
        integer :: unit = -1
        character(len = :), allocatable :: name
        logical :: is_open = .false., mode_read = .false., mode_write = .false.
        logical :: eof = .false.
        logical :: is_std = .false.
    end type rt_file_t

    ! Whether reading from stdin has hit the end of input, for the forms of
    ! readln() and eof() with no argument
    logical, save :: rt_stdin_eof = .false.

    ! Convert a scalar to a string exactly like syntran's println()/str() do.
    ! Note that the real kinds are *not* trimmed, for column alignment
    interface rt_str
        module procedure rt_str_bool, rt_str_i32, rt_str_i64, rt_str_f32, rt_str_f64, rt_str_str
    end interface rt_str

    ! Convert an array of rank 1 to 4 to a string, like rt_str() does for a scalar.
    ! These have explicit ranks and call the assumed-rank rt_str_a_<type> below,
    ! because gfortran mishandles an empty array *expression* that is passed
    ! straight to an assumed-rank dummy argument
    interface rt_str_a
        module procedure rt_str_a_bool_1, rt_str_a_bool_2, rt_str_a_bool_3, &
            rt_str_a_bool_4, rt_str_a_i32_1, rt_str_a_i32_2, rt_str_a_i32_3, &
            rt_str_a_i32_4, rt_str_a_i64_1, rt_str_a_i64_2, rt_str_a_i64_3, &
            rt_str_a_i64_4, rt_str_a_f32_1, rt_str_a_f32_2, rt_str_a_f32_3, &
            rt_str_a_f32_4, rt_str_a_f64_1, rt_str_a_f64_2, rt_str_a_f64_3, &
            rt_str_a_f64_4, rt_str_a_str_1, rt_str_a_str_2, rt_str_a_str_3, &
            rt_str_a_str_4
    end interface rt_str_a

    ! Convert an array that is a member of a struct to a string, which also
    ! writes how the type of its elements is given, like `[1'i64, 2'i64]`
    interface rt_str_a_rt
        module procedure rt_str_a_rt_i64, rt_str_a_rt_f32, rt_str_a_rt_str
    end interface rt_str_a_rt

    ! Whole-array equality of two arrays of the same rank, given as shapes and
    ! flattened elements: one bool, false if the shapes differ
    interface rt_arr_eq
        module procedure rt_arr_eq_bool, rt_arr_eq_i32, rt_arr_eq_i64, rt_arr_eq_f32, &
            rt_arr_eq_f64, rt_arr_eq_str
    end interface rt_arr_eq

contains

!===============================================================================

function rt_str_bool(x) result(s)
    logical, intent(in) :: x
    character(len = :), allocatable :: s
    if (x) then
        s = 'true'
    else
        s = 'false'
    end if
end function rt_str_bool

!===============================================================================

function rt_str_i32(x) result(s)
    integer(int32), intent(in) :: x
    character(len = :), allocatable :: s
    character(len = 16) :: buf
    write(buf, '(i0)') x
    s = trim(buf)
end function rt_str_i32

!===============================================================================

function rt_str_i64(x) result(s)
    integer(int64), intent(in) :: x
    character(len = :), allocatable :: s
    character(len = 24) :: buf
    write(buf, '(i0)') x
    s = trim(buf)
end function rt_str_i64

!===============================================================================

function rt_str_f32(x) result(s)
    real(real32), intent(in) :: x
    character(len = :), allocatable :: s
    character(len = 16) :: buf
    write(buf, '(es16.6)') x
    s = buf
end function rt_str_f32

!===============================================================================

function rt_str_f64(x) result(s)
    real(real64), intent(in) :: x
    character(len = :), allocatable :: s
    character(len = 28) :: buf
    write(buf, '(es25.15)') x
    s = buf
end function rt_str_f64

!===============================================================================

function rt_str_str(x) result(s)
    character(len = *), intent(in) :: x
    character(len = :), allocatable :: s
    s = x
end function rt_str_str

!===============================================================================

! Equality of two strings.  Fortran's `==` pads the shorter operand with blanks,
! so "a" == "a " would be true, unlike in syntran
pure function rt_str_eq(a, b) result(eq)
    character(len = *), intent(in) :: a, b
    logical :: eq
    eq = len(a) == len(b)
    if (eq) eq = a == b
end function rt_str_eq

!===============================================================================

! Length-aware lexicographic string less-than.  Fortran's `<` blank-pads the
! shorter operand first, so "a" < "a " would be false.  A string that is a
! strict prefix of another sorts first.  The other orderings derive from this:
!
!     a <= b  =  .not. rt_str_lt(b, a)
!     a >  b  =  rt_str_lt(b, a)
!     a >= b  =  .not. rt_str_lt(a, b)
pure function rt_str_lt(a, b) result(lt)
    character(len = *), intent(in) :: a, b
    logical :: lt
    integer :: i, n
    n = min(len(a), len(b))
    do i = 1, n
        if (a(i:i) /= b(i:i)) then
            lt = a(i:i) < b(i:i)
            return
        end if
    end do
    lt = len(a) < len(b)
end function rt_str_lt

!===============================================================================

! s[i], with a 0-based index.  This is for when the index is an expression which
! mustn't be evaluated twice
function rt_char_at(s, i) result(c)
    character(len = *), intent(in) :: s
    integer(int64), intent(in) :: i
    character(len = 1) :: c
    c = s(i + 1: i + 1)
end function rt_char_at

!===============================================================================

! The 0-based indices of s[lb: step: ub] for a string of length n.  An omitted
! bound depends on the sign of the step, like the interpreter's.  The bound is
! exclusive
function rt_str_step_idx(n, step, lb, ub) result(r)
    integer(int64), intent(in) :: n, step
    integer(int64), intent(in), optional :: lb, ub
    integer(int64), allocatable :: r(:)
    integer(int64) :: lb_, ub_
    if (step == 0) call rt_fatal('subscript step is 0')
    lb_ = 0
    if (step < 0) lb_ = n - 1
    ub_ = n
    if (step < 0) ub_ = -1
    if (present(lb)) lb_ = lb
    if (present(ub)) ub_ = ub
    r = rt_step_i64(lb_, step, ub_)
end function rt_str_step_idx

! s[lb: step: ub], like a reversed `s[:-1:]`
function rt_str_step(s, step, lb, ub) result(r)
    character(len = *), intent(in) :: s
    integer(int64), intent(in) :: step
    integer(int64), intent(in), optional :: lb, ub
    character(len = :), allocatable :: r
    integer(int64), allocatable :: idx(:)
    integer :: i
    idx = rt_str_step_idx(int(len(s), int64), step, lb, ub)
    allocate(character(len = size(idx)) :: r)
    do i = 1, size(idx)
        r(i:i) = s(idx(i) + 1: idx(i) + 1)
    end do
end function rt_str_step

! s[lb: step: ub] = rhs
subroutine rt_str_step_set(s, rhs, step, lb, ub)
    character(len = *), intent(inout) :: s
    character(len = *), intent(in) :: rhs
    integer(int64), intent(in) :: step
    integer(int64), intent(in), optional :: lb, ub
    integer(int64), allocatable :: idx(:)
    integer :: i
    idx = rt_str_step_idx(int(len(s), int64), step, lb, ub)
    if (size(idx) /= len(rhs)) &
        call rt_fatal('size of RHS does not match size of LHS slice')
    do i = 1, size(idx)
        s(idx(i) + 1: idx(i) + 1) = rhs(i:i)
    end do
end subroutine rt_str_step_set

!===============================================================================

! println() writes all of its arguments, which the caller has joined, as one line
subroutine rt_println(s)
    character(len = *), intent(in) :: s
    write(output_unit, '(a)') s
end subroutine rt_println

!===============================================================================

! exit() says so, then terminates the program with the given status
subroutine rt_exit(code)
    integer(int32), intent(in) :: code
    write(output_unit, *) 'Exiting syntran with status '//rt_str_i32(code)
    stop code, quiet = .true.
end subroutine rt_exit

!===============================================================================

! The CLI prints the value of the program's last statement after it finishes,
! indented with 4 spaces (and a 5th from list-directed output)
subroutine rt_result(s)
    character(len = *), intent(in) :: s
    write(output_unit, *) '    '//s
end subroutine rt_result

!===============================================================================

! A runtime error is fatal.  Compile with -fcheck=all to also catch subscripts
! which are out of bounds
subroutine rt_fatal(msg)
    character(len = *), intent(in) :: msg
    write(error_unit, '(a)') 'Runtime error: '//msg
    error stop 1
end subroutine rt_fatal

!===============================================================================

! Arrays of strings are built element by element.  Fortran's spread() and
! reshape() copy an array of a type with an allocatable component shallowly, so
! the strings of the result would dangle once the argument is freed

function rt_fill_str(s, n) result(r)
    character(len = *), intent(in) :: s
    integer(int64), intent(in) :: n
    type(rt_str_t), allocatable :: r(:)
    integer(int64) :: i
    allocate(r(max(0_int64, n)))
    do i = 1, n
        r(i)%s = s
    end do
end function rt_fill_str

function rt_reshape_str_2(a, n1, n2) result(r)
    type(rt_str_t), intent(in) :: a(:)
    integer(int64), intent(in) :: n1, n2
    type(rt_str_t), allocatable :: r(:,:)
    integer(int64) :: i, j, k
    if (n1 * n2 /= size(a)) call rt_fatal('array size does not match its shape')
    allocate(r(n1, n2))
    k = 0
    do j = 1, n2
        do i = 1, n1
            k = k + 1
            r(i, j)%s = a(k)%s
        end do
    end do
end function rt_reshape_str_2

function rt_reshape_str_3(a, n1, n2, n3) result(r)
    type(rt_str_t), intent(in) :: a(:)
    integer(int64), intent(in) :: n1, n2, n3
    type(rt_str_t), allocatable :: r(:,:,:)
    integer(int64) :: i, j, l, k
    if (n1 * n2 * n3 /= size(a)) call rt_fatal('array size does not match its shape')
    allocate(r(n1, n2, n3))
    k = 0
    do l = 1, n3
        do j = 1, n2
            do i = 1, n1
                k = k + 1
                r(i, j, l)%s = a(k)%s
            end do
        end do
    end do
end function rt_reshape_str_3

function rt_reshape_str_4(a, n1, n2, n3, n4) result(r)
    type(rt_str_t), intent(in) :: a(:)
    integer(int64), intent(in) :: n1, n2, n3, n4
    type(rt_str_t), allocatable :: r(:,:,:,:)
    integer(int64) :: i, j, l, m, k
    if (n1 * n2 * n3 * n4 /= size(a)) call rt_fatal('array size does not match its shape')
    allocate(r(n1, n2, n3, n4))
    k = 0
    do m = 1, n4
        do l = 1, n3
            do j = 1, n2
                do i = 1, n1
                    k = k + 1
                    r(i, j, l, m)%s = a(k)%s
                end do
            end do
        end do
    end do
end function rt_reshape_str_4

!===============================================================================

! Convert a string to a number, like the interpreter's parse_*() fns do.  A
! string which isn't a number is a fatal error

function rt_parse_i32(s) result(r)
    character(len = *), intent(in) :: s
    integer(int32) :: r
    integer :: io
    read(s, *, iostat = io) r
    if (io /= 0) call rt_fatal(' cannot parse_i32() for argument `'//s//'`')
end function rt_parse_i32

function rt_parse_i64(s) result(r)
    character(len = *), intent(in) :: s
    integer(int64) :: r
    integer :: io
    read(s, *, iostat = io) r
    if (io /= 0) call rt_fatal(' cannot parse_i64() for argument `'//s//'`')
end function rt_parse_i64

function rt_parse_f32(s) result(r)
    character(len = *), intent(in) :: s
    real(real32) :: r
    integer :: io
    read(s, *, iostat = io) r
    if (io /= 0) call rt_fatal(' cannot parse_f32() for argument `'//s//'`')
end function rt_parse_f32

function rt_parse_f64(s) result(r)
    character(len = *), intent(in) :: s
    real(real64) :: r
    integer :: io
    read(s, *, iostat = io) r
    if (io /= 0) call rt_fatal(' cannot parse_f64() for argument `'//s//'`')
end function rt_parse_f64

!===============================================================================

! The array [lb: ub], which is empty if ub <= lb
function rt_range_i32(lb, ub) result(r)
    integer(int32), intent(in) :: lb, ub
    integer(int32), allocatable :: r(:)
    integer(int32) :: i
    r = [(i, i = lb, ub - 1_int32)]
end function rt_range_i32

function rt_range_i64(lb, ub) result(r)
    integer(int64), intent(in) :: lb, ub
    integer(int64), allocatable :: r(:)
    integer(int64) :: i
    r = [(i, i = lb, ub - 1_int64)]
end function rt_range_i64

!===============================================================================

! The array [lb: step: ub].  The bound is exclusive and the step may be
! negative.  This is the same algorithm as the interpreter's, including its
! "(i < ub) .eqv. (lb < ub)" loop condition, so that results are identical

function rt_step_i32(lb, step, ub) result(r)
    integer(int32), intent(in) :: lb, step, ub
    integer(int32), allocatable :: r(:)
    integer(int32) :: i
    integer :: j, cap
    if (step == 0) call rt_fatal('array step is 0')
    cap = max(0, (ub - lb + step - sign(1_int32, step)) / step)
    allocate(r(cap))
    j = 1
    i = lb
    if ((lb < ub) .neqv. (0 < step)) i = ub
    do while (((i < ub) .eqv. (lb < ub)) .and. i /= ub)
        r(j) = i
        i = i + step
        j = j + 1
    end do
    r = r(1: j - 1)
end function rt_step_i32

function rt_step_i64(lb, step, ub) result(r)
    integer(int64), intent(in) :: lb, step, ub
    integer(int64), allocatable :: r(:)
    integer(int64) :: i
    integer :: j, cap
    if (step == 0) call rt_fatal('array step is 0')
    cap = int(max(0_int64, (ub - lb + step - sign(1_int64, step)) / step))
    allocate(r(cap))
    j = 1
    i = lb
    if ((lb < ub) .neqv. (0 < step)) i = ub
    do while (((i < ub) .eqv. (lb < ub)) .and. i /= ub)
        r(j) = i
        i = i + step
        j = j + 1
    end do
    r = r(1: j - 1)
end function rt_step_i64

function rt_step_f32(lb, step, ub) result(r)
    real(real32), intent(in) :: lb, step, ub
    real(real32), allocatable :: r(:)
    real(real32) :: f
    integer :: j, cap
    if (.not. (step > 0.0_real32 .or. step < 0.0_real32)) call rt_fatal('array step is 0.0')
    cap = max(0, ceiling((ub - lb) / step))
    allocate(r(cap))
    j = 1
    f = lb
    if ((lb < ub) .neqv. (0 < step)) f = ub
    do while (((f < ub) .eqv. (lb < ub)) .and. (f < ub .or. f > ub))
        r(j) = f
        ! Multiplying instead of repeatedly adding keeps rounding errors from
        ! accumulating, e.g. [0.0: 0.1: 0.9]
        f = lb + j * step
        j = j + 1
    end do
    r = r(1: j - 1)
end function rt_step_f32

function rt_step_f64(lb, step, ub) result(r)
    real(real64), intent(in) :: lb, step, ub
    real(real64), allocatable :: r(:)
    real(real64) :: f
    integer :: j, cap
    if (.not. (step > 0.0_real64 .or. step < 0.0_real64)) call rt_fatal('array step is 0.0')
    cap = max(0, ceiling((ub - lb) / step))
    allocate(r(cap))
    j = 1
    f = lb
    if ((lb < ub) .neqv. (0 < step)) f = ub
    do while (((f < ub) .eqv. (lb < ub)) .and. (f < ub .or. f > ub))
        r(j) = f
        f = lb + j * step
        j = j + 1
    end do
    r = r(1: j - 1)
end function rt_step_f64

!===============================================================================

! The array [lb: ub; n] of n evenly spaced values, including both ends

function rt_linspace_f32(lb, ub, n) result(r)
    real(real32), intent(in) :: lb, ub
    integer(int64), intent(in) :: n
    real(real32), allocatable :: r(:)
    real(real32) :: dx
    integer :: i
    allocate(r(max(0_int64, n)))
    dx = (ub - lb) / real(n - 1)
    do i = 0, int(n) - 1
        r(i + 1) = lb + i * dx
    end do
end function rt_linspace_f32

function rt_linspace_f64(lb, ub, n) result(r)
    real(real64), intent(in) :: lb, ub
    integer(int64), intent(in) :: n
    real(real64), allocatable :: r(:)
    real(real64) :: dx
    integer :: i
    allocate(r(max(0_int64, n)))
    dx = (ub - lb) / real(n - 1, real64)
    do i = 0, int(n) - 1
        r(i + 1) = lb + i * dx
    end do
end function rt_linspace_f64

!===============================================================================

! Join the already-formatted elements of an array of shape `shp`, which are in
! storage (column-major) order.  Elements are separated by ", ".  A rank > 1
! array starts and ends with a line break, and also has one after every
! complete row (and plane, etc.), exactly like the interpreter prints them
function rt_join(items, shp) result(s)
    type(rt_str_t), intent(in) :: items(:)
    integer, intent(in) :: shp(:)
    character(len = :), allocatable :: s

    character(len = :), allocatable :: buf
    integer :: i, j, n, pos, prod, need
    character, parameter :: lf = achar(10)

    n = size(items)
    allocate(character(len = 64) :: buf)
    pos = 0

    call put('[')
    if (size(shp) > 1) call put(lf)

    do i = 1, n
        call put(items(i)%s)
        if (i >= n) cycle
        call put(', ')

        prod = shp(1)
        do j = 2, size(shp)
            if (mod(i, prod) == 0) call put(lf)
            prod = prod * shp(j)
        end do
    end do

    if (size(shp) > 1) call put(lf)
    call put(']')

    s = buf(1: pos)

contains

    ! Append to the buffer, doubling its capacity as needed
    subroutine put(str)
        character(len = *), intent(in) :: str
        character(len = :), allocatable :: tmp
        need = pos + len(str)
        if (need > len(buf)) then
            allocate(character(len = max(need, 2 * len(buf))) :: tmp)
            tmp(1: pos) = buf(1: pos)
            call move_alloc(tmp, buf)
        end if
        buf(pos + 1: need) = str
        pos = need
    end subroutine put

end function rt_join

!===============================================================================

function rt_str_a_bool(x) result(s)
    logical, intent(in) :: x(..)
    character(len = :), allocatable :: s
    select rank (x)
    rank (1)
        s = rt_join(items(x), shape(x))
    rank (2)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (3)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (4)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank default
        call rt_fatal('arrays of rank > 4 are not supported by rt_str_a()')
    end select
contains
    function items(a) result(r)
        logical, intent(in) :: a(:)
        type(rt_str_t), allocatable :: r(:)
        integer :: i
        allocate(r(size(a)))
        do i = 1, size(a)
            r(i)%s = rt_str_bool(a(i))
        end do
    end function items
end function rt_str_a_bool

function rt_str_a_i32(x) result(s)
    integer(int32), intent(in) :: x(..)
    character(len = :), allocatable :: s
    select rank (x)
    rank (1)
        s = rt_join(items(x), shape(x))
    rank (2)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (3)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (4)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank default
        call rt_fatal('arrays of rank > 4 are not supported by rt_str_a()')
    end select
contains
    function items(a) result(r)
        integer(int32), intent(in) :: a(:)
        type(rt_str_t), allocatable :: r(:)
        integer :: i
        allocate(r(size(a)))
        do i = 1, size(a)
            r(i)%s = rt_str_i32(a(i))
        end do
    end function items
end function rt_str_a_i32

function rt_str_a_i64(x) result(s)
    integer(int64), intent(in) :: x(..)
    character(len = :), allocatable :: s
    select rank (x)
    rank (1)
        s = rt_join(items(x), shape(x))
    rank (2)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (3)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (4)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank default
        call rt_fatal('arrays of rank > 4 are not supported by rt_str_a()')
    end select
contains
    function items(a) result(r)
        integer(int64), intent(in) :: a(:)
        type(rt_str_t), allocatable :: r(:)
        integer :: i
        allocate(r(size(a)))
        do i = 1, size(a)
            r(i)%s = rt_str_i64(a(i))
        end do
    end function items
end function rt_str_a_i64

! The elements of a real array are trimmed, unlike a scalar's
function rt_str_a_f32(x) result(s)
    real(real32), intent(in) :: x(..)
    character(len = :), allocatable :: s
    select rank (x)
    rank (1)
        s = rt_join(items(x), shape(x))
    rank (2)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (3)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (4)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank default
        call rt_fatal('arrays of rank > 4 are not supported by rt_str_a()')
    end select
contains
    function items(a) result(r)
        real(real32), intent(in) :: a(:)
        type(rt_str_t), allocatable :: r(:)
        integer :: i
        allocate(r(size(a)))
        do i = 1, size(a)
            r(i)%s = trim(adjustl(rt_str_f32(a(i))))
        end do
    end function items
end function rt_str_a_f32

function rt_str_a_f64(x) result(s)
    real(real64), intent(in) :: x(..)
    character(len = :), allocatable :: s
    select rank (x)
    rank (1)
        s = rt_join(items(x), shape(x))
    rank (2)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (3)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (4)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank default
        call rt_fatal('arrays of rank > 4 are not supported by rt_str_a()')
    end select
contains
    function items(a) result(r)
        real(real64), intent(in) :: a(:)
        type(rt_str_t), allocatable :: r(:)
        integer :: i
        allocate(r(size(a)))
        do i = 1, size(a)
            r(i)%s = trim(adjustl(rt_str_f64(a(i))))
        end do
    end function items
end function rt_str_a_f64

function rt_str_a_str(x) result(s)
    type(rt_str_t), intent(in) :: x(..)
    character(len = :), allocatable :: s
    select rank (x)
    rank (1)
        s = rt_join(x, shape(x))
    rank (2)
        s = rt_join(reshape(x, [size(x)]), shape(x))
    rank (3)
        s = rt_join(reshape(x, [size(x)]), shape(x))
    rank (4)
        s = rt_join(reshape(x, [size(x)]), shape(x))
    rank default
        call rt_fatal('arrays of rank > 4 are not supported by rt_str_a()')
    end select
end function rt_str_a_str

!===============================================================================

function rt_str_a_bool_1(x) result(s)
    logical, intent(in) :: x(:)
    character(len = :), allocatable :: s
    s = rt_str_a_bool(x)
end function rt_str_a_bool_1

function rt_str_a_bool_2(x) result(s)
    logical, intent(in) :: x(:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_bool(x)
end function rt_str_a_bool_2

function rt_str_a_bool_3(x) result(s)
    logical, intent(in) :: x(:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_bool(x)
end function rt_str_a_bool_3

function rt_str_a_bool_4(x) result(s)
    logical, intent(in) :: x(:,:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_bool(x)
end function rt_str_a_bool_4

function rt_str_a_i32_1(x) result(s)
    integer(int32), intent(in) :: x(:)
    character(len = :), allocatable :: s
    s = rt_str_a_i32(x)
end function rt_str_a_i32_1

function rt_str_a_i32_2(x) result(s)
    integer(int32), intent(in) :: x(:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_i32(x)
end function rt_str_a_i32_2

function rt_str_a_i32_3(x) result(s)
    integer(int32), intent(in) :: x(:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_i32(x)
end function rt_str_a_i32_3

function rt_str_a_i32_4(x) result(s)
    integer(int32), intent(in) :: x(:,:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_i32(x)
end function rt_str_a_i32_4

function rt_str_a_i64_1(x) result(s)
    integer(int64), intent(in) :: x(:)
    character(len = :), allocatable :: s
    s = rt_str_a_i64(x)
end function rt_str_a_i64_1

function rt_str_a_i64_2(x) result(s)
    integer(int64), intent(in) :: x(:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_i64(x)
end function rt_str_a_i64_2

function rt_str_a_i64_3(x) result(s)
    integer(int64), intent(in) :: x(:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_i64(x)
end function rt_str_a_i64_3

function rt_str_a_i64_4(x) result(s)
    integer(int64), intent(in) :: x(:,:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_i64(x)
end function rt_str_a_i64_4

function rt_str_a_f32_1(x) result(s)
    real(real32), intent(in) :: x(:)
    character(len = :), allocatable :: s
    s = rt_str_a_f32(x)
end function rt_str_a_f32_1

function rt_str_a_f32_2(x) result(s)
    real(real32), intent(in) :: x(:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_f32(x)
end function rt_str_a_f32_2

function rt_str_a_f32_3(x) result(s)
    real(real32), intent(in) :: x(:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_f32(x)
end function rt_str_a_f32_3

function rt_str_a_f32_4(x) result(s)
    real(real32), intent(in) :: x(:,:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_f32(x)
end function rt_str_a_f32_4

function rt_str_a_f64_1(x) result(s)
    real(real64), intent(in) :: x(:)
    character(len = :), allocatable :: s
    s = rt_str_a_f64(x)
end function rt_str_a_f64_1

function rt_str_a_f64_2(x) result(s)
    real(real64), intent(in) :: x(:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_f64(x)
end function rt_str_a_f64_2

function rt_str_a_f64_3(x) result(s)
    real(real64), intent(in) :: x(:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_f64(x)
end function rt_str_a_f64_3

function rt_str_a_f64_4(x) result(s)
    real(real64), intent(in) :: x(:,:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_f64(x)
end function rt_str_a_f64_4

function rt_str_a_str_1(x) result(s)
    type(rt_str_t), intent(in) :: x(:)
    character(len = :), allocatable :: s
    s = rt_str_a_str(x)
end function rt_str_a_str_1

function rt_str_a_str_2(x) result(s)
    type(rt_str_t), intent(in) :: x(:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_str(x)
end function rt_str_a_str_2

function rt_str_a_str_3(x) result(s)
    type(rt_str_t), intent(in) :: x(:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_str(x)
end function rt_str_a_str_3

function rt_str_a_str_4(x) result(s)
    type(rt_str_t), intent(in) :: x(:,:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_str(x)
end function rt_str_a_str_4

!===============================================================================

! Elemental versions of the operators that Fortran doesn't have for the
! strings in an array of rt_str_t

elemental function rt_cat(a, b) result(r)
    type(rt_str_t), intent(in) :: a, b
    type(rt_str_t) :: r
    r%s = a%s // b%s
end function rt_cat

elemental function rt_eq(a, b) result(r)
    type(rt_str_t), intent(in) :: a, b
    logical :: r
    r = rt_str_eq(a%s, b%s)
end function rt_eq

elemental function rt_lt(a, b) result(r)
    type(rt_str_t), intent(in) :: a, b
    logical :: r
    r = rt_str_lt(a%s, b%s)
end function rt_lt

elemental function rt_str_t_of(s) result(r)
    character(len = *), intent(in) :: s
    type(rt_str_t) :: r
    r%s = s
end function rt_str_t_of

!===============================================================================

function rt_str_a_rt_i64(x) result(s)
    integer(int64), intent(in) :: x(..)
    character(len = :), allocatable :: s
    select rank (x)
    rank (1)
        s = rt_join(items(x), shape(x))
    rank (2)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (3)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (4)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank default
        call rt_fatal('arrays of rank > 4 are not supported by rt_str_a_rt()')
    end select
contains
    function items(a) result(r)
        integer(int64), intent(in) :: a(:)
        type(rt_str_t), allocatable :: r(:)
        integer :: i
        allocate(r(size(a)))
        do i = 1, size(a)
            r(i)%s = rt_str_i64(a(i)) // "'i64"
        end do
    end function items
end function rt_str_a_rt_i64

function rt_str_a_rt_f32(x) result(s)
    real(real32), intent(in) :: x(..)
    character(len = :), allocatable :: s
    select rank (x)
    rank (1)
        s = rt_join(items(x), shape(x))
    rank (2)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (3)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (4)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank default
        call rt_fatal('arrays of rank > 4 are not supported by rt_str_a_rt()')
    end select
contains
    function items(a) result(r)
        real(real32), intent(in) :: a(:)
        type(rt_str_t), allocatable :: r(:)
        integer :: i
        allocate(r(size(a)))
        do i = 1, size(a)
            r(i)%s = trim(adjustl(rt_str_f32(a(i)))) // "'f32"
        end do
    end function items
end function rt_str_a_rt_f32

function rt_str_a_rt_str(x) result(s)
    type(rt_str_t), intent(in) :: x(..)
    character(len = :), allocatable :: s
    select rank (x)
    rank (1)
        s = rt_join(items(x), shape(x))
    rank (2)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (3)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (4)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank default
        call rt_fatal('arrays of rank > 4 are not supported by rt_str_a_rt()')
    end select
contains
    function items(a) result(r)
        type(rt_str_t), intent(in) :: a(:)
        type(rt_str_t), allocatable :: r(:)
        integer :: i
        allocate(r(size(a)))
        do i = 1, size(a)
            r(i)%s = rt_quote(a(i)%s)
        end do
    end function items
end function rt_str_a_rt_str

!===============================================================================

!===============================================================================

! File I/O.  A failure is fatal, where the interpreter's is a runtime error

function rt_read_line(iu, iostat) result(s)
    ! Reads one character at a time, so that it works on stdin too
    integer, intent(in) :: iu
    integer, intent(out) :: iostat
    character(len = :), allocatable :: s
    character :: c
    character(len = 256) :: buf
    integer :: io, n
    s = ''
    n = 0
    do
        read(iu, '(a)', advance = 'no', iostat = io) c
        if (io /= 0) exit
        n = n + 1
        buf(n:n) = c
        if (n == len(buf)) then
            s = s // buf(1:n)
            n = 0
        end if
    end do
    if (n > 0) s = s // buf(1:n)
    iostat = io
end function rt_read_line

function rt_open(name, mode, must_open) result(f)
    character(len = *), intent(in) :: name, mode
    logical, intent(in) :: must_open
    type(rt_file_t) :: f
    character(len = :), allocatable :: status
    integer :: i, io
    f%name = name
    f%unit = -1
    do i = 1, len(mode)
        select case (mode(i:i))
        case ('r')
            f%mode_read = .true.
        case ('w')
            f%mode_write = .true.
        case default
            call rt_fatal('bad file mode character "' // mode(i:i) // '"')
        end select
    end do
    if (f%mode_read .and. f%mode_write) then
        call rt_fatal('cannot open file "' // name // '" in combined read/write mode "' &
            // mode // '"')
    end if
    if (f%mode_read) then
        status = 'old'
    else
        status = 'unknown'
    end if
    open(newunit = f%unit, file = name, status = status, iostat = io)
    if (io /= 0) then
        f%unit = -1
        if (must_open) call rt_fatal('cannot open file "' // name // '"')
        return
    end if
    f%eof = .false.
    f%is_open = .true.
end function rt_open

subroutine rt_close(f)
    type(rt_file_t), intent(inout) :: f
    integer :: io
    if (f%is_std) then
        call rt_fatal('close() cannot be called on standard file handle "' // f%name // '"')
    end if
    if (.not. f%is_open) then
        call rt_fatal('close() was called for file "' // f%name // '" which is not open')
    end if
    f%is_open = .false.
    close(f%unit, iostat = io)
    if (io /= 0) call rt_fatal('cannot close() file "' // f%name // '"')
end subroutine rt_close

function rt_readln(f) result(s)
    type(rt_file_t), intent(inout) :: f
    character(len = :), allocatable :: s
    integer :: io
    if (.not. f%is_open) then
        call rt_fatal('readln() was called for file "' // f%name // '" which is not open')
    end if
    if (.not. f%mode_read) then
        call rt_fatal('readln() was called for file "' // f%name // &
            '" which was not opened in read mode "r"')
    end if
    if (f%is_std) f%eof = rt_stdin_eof
    if (f%eof) then
        call rt_fatal('cannot readln() from file "' // f%name // '" past end of file')
    end if
    s = rt_read_line(f%unit, io)
    if (io == iostat_end) then
        f%eof = .true.
        if (f%is_std) rt_stdin_eof = .true.
    else if (io /= 0 .and. io /= iostat_eor) then
        call rt_fatal('cannot readln() from file "' // f%name // '"')
    end if
end function rt_readln

function rt_readln_stdin() result(s)
    character(len = :), allocatable :: s
    integer :: io
    if (rt_stdin_eof) call rt_fatal('cannot readln() from stdin past end of input')
    s = rt_read_line(input_unit, io)
    if (io == iostat_end) then
        rt_stdin_eof = .true.
    else if (io /= 0 .and. io /= iostat_eor) then
        call rt_fatal('cannot readln() from stdin')
    end if
end function rt_readln_stdin

function rt_eof(f) result(r)
    type(rt_file_t), intent(in) :: f
    logical :: r
    if (.not. f%is_open) then
        call rt_fatal('eof() was called for file "' // f%name // '" which is not open')
    end if
    if (.not. f%mode_read) then
        call rt_fatal('eof() was called for file "' // f%name // &
            '" which was not opened in read mode "r"')
    end if
    r = f%eof
    if (f%is_std) r = rt_stdin_eof
end function rt_eof

function rt_std_file(k) result(f)
    ! std::IN, std::OUT, and std::ERR, which are the 2nd, 3rd, and 4th of the
    ! constants of `std::`
    integer, intent(in) :: k
    type(rt_file_t) :: f
    f%is_open = .true.
    f%is_std = .true.
    select case (k)
    case (2)
        f%name = 'stdin'
        f%unit = input_unit
        f%mode_read = .true.
    case (3)
        f%name = 'stdout'
        f%unit = output_unit
        f%mode_write = .true.
    case default
        f%name = 'stderr'
        f%unit = error_unit
        f%mode_write = .true.
    end select
end function rt_std_file

function rt_eof_stdin() result(r)
    logical :: r
    r = rt_stdin_eof
end function rt_eof_stdin

! writeln() writes all of its values after the file, which the caller has joined,
! as one line
subroutine rt_writeln(f, s)
    type(rt_file_t), intent(in) :: f
    character(len = *), intent(in) :: s
    integer :: io
    if (.not. f%is_open) then
        call rt_fatal('writeln() was called for file "' // f%name // '" which is not open')
    end if
    if (.not. f%mode_write) then
        call rt_fatal('writeln() was called for file "' // f%name // &
            '" which was not opened in write mode "w"')
    end if
    write(f%unit, '(a)', iostat = io) s
    if (io /= 0) call rt_fatal('cannot writeln() to file "' // f%name // '"')
end subroutine rt_writeln

function rt_exists(path) result(r)
    character(len = *), intent(in) :: path
    logical :: r
    inquire(file = path, exist = r)
end function rt_exists

function rt_getenv(name) result(s)
    character(len = *), intent(in) :: name
    character(len = :), allocatable :: s
    integer :: n, st
    call get_environment_variable(name, length = n, status = st)
    if (st /= 0) call rt_fatal('environment variable "' // name // '" is not set')
    allocate(character(len = n) :: s)
    if (n > 0) call get_environment_variable(name, value = s)
end function rt_getenv

function rt_hasenv(name) result(r)
    character(len = *), intent(in) :: name
    logical :: r
    integer :: st
    call get_environment_variable(name, status = st)
    r = st == 0
end function rt_hasenv

function rt_args() result(r)
    ! The command line arguments of the program
    type(rt_str_t), allocatable :: r(:)
    integer :: i, n, m
    n = command_argument_count()
    allocate(r(n))
    do i = 1, n
        call get_command_argument(i, length = m)
        allocate(character(len = m) :: r(i)%s)
        if (m > 0) call get_command_argument(i, value = r(i)%s)
    end do
end function rt_args

!===============================================================================

! A string as a struct prints it, in double quotes with any quote doubled

function rt_quote(s) result(r)
    character(len = *), intent(in) :: s
    character(len = :), allocatable :: r
    integer :: i
    r = '"'
    do i = 1, len(s)
        if (s(i:i) == '"') r = r // '"'
        r = r // s(i:i)
    end do
    r = r // '"'
end function rt_quote

!===============================================================================

! The elements of an array of structs, which are already joined, in brackets.
! An array of rank > 1 has a line feed after the opening and before the closing
! bracket, but not between its rows

function rt_arr_wrap(joined, rank_) result(r)
    character(len = *), intent(in) :: joined
    integer, intent(in) :: rank_
    character(len = :), allocatable :: r
    if (rank_ > 1) then
        r = '[' // new_line('a') // joined // new_line('a') // ']'
    else
        r = '[' // joined // ']'
    end if
end function rt_arr_wrap

!===============================================================================

! Whole-array equality, for the match of a `switch` on an array.  Unlike the
! elementwise `==` it is a single bool, and arrays of different shapes are just
! not equal.  Each array is passed as its shape and its elements flattened to
! rank 1, like `rt_arr_eq(shape(a), reshape(a, [size(a)]), shape(b), ...)`.  That
! is for any rank, and it avoids an assumed-rank dummy argument, which gfortran
! gets wrong for an empty array expression

function rt_arr_eq_bool(sa, va, sb, vb) result(r)
    integer, intent(in) :: sa(:), sb(:)
    logical, intent(in) :: va(:), vb(:)
    logical :: r
    r = .false.
    if (size(sa) /= size(sb)) return
    if (any(sa /= sb)) return
    r = all(va .eqv. vb)
end function rt_arr_eq_bool

function rt_arr_eq_i32(sa, va, sb, vb) result(r)
    integer, intent(in) :: sa(:), sb(:)
    integer(int32), intent(in) :: va(:), vb(:)
    logical :: r
    r = .false.
    if (size(sa) /= size(sb)) return
    if (any(sa /= sb)) return
    r = all(va == vb)
end function rt_arr_eq_i32

function rt_arr_eq_i64(sa, va, sb, vb) result(r)
    integer, intent(in) :: sa(:), sb(:)
    integer(int64), intent(in) :: va(:), vb(:)
    logical :: r
    r = .false.
    if (size(sa) /= size(sb)) return
    if (any(sa /= sb)) return
    r = all(va == vb)
end function rt_arr_eq_i64

function rt_arr_eq_f32(sa, va, sb, vb) result(r)
    integer, intent(in) :: sa(:), sb(:)
    real(real32), intent(in) :: va(:), vb(:)
    logical :: r
    r = .false.
    if (size(sa) /= size(sb)) return
    if (any(sa /= sb)) return
    r = all(va == vb)
end function rt_arr_eq_f32

function rt_arr_eq_f64(sa, va, sb, vb) result(r)
    integer, intent(in) :: sa(:), sb(:)
    real(real64), intent(in) :: va(:), vb(:)
    logical :: r
    r = .false.
    if (size(sa) /= size(sb)) return
    if (any(sa /= sb)) return
    r = all(va == vb)
end function rt_arr_eq_f64

function rt_arr_eq_str(sa, va, sb, vb) result(r)
    integer, intent(in) :: sa(:), sb(:)
    type(rt_str_t), intent(in) :: va(:), vb(:)
    logical :: r
    r = .false.
    if (size(sa) /= size(sb)) return
    if (any(sa /= sb)) return
    r = all(rt_eq(va, vb))
end function rt_arr_eq_str

!===============================================================================

end module syntran_rt

!===============================================================================

