
!===============================================================================

! Runtime support for Fortran programs generated by `syntran --transpile`.
!
! This file is embedded verbatim at the top of every transpiled program, so it
! must be a self-contained, standard-conforming Fortran module with no
! dependencies other than the Fortran standard library.  Use *spaces* for
! indentation here, unlike the rest of the syntran sources: a tab character is
! nonstandard in free-form Fortran and gfortran warns about it in user programs.
!
! It is also compiled into the syntran library itself, so the compiler checks
! it on every normal build and the unit tests can call it directly.
!
! After editing, regenerate src/transpile_rt.f90 with src/gen_transpile_rt.sh.
! Keep lines under 100 characters.
!
! Naming: every public name starts with `rt_` and must NOT end in `_g<digits>`,
! `_l<digits>`, or `_f<digits>`, which is the shape of every name generated for
! a syntran variable or function.  That guarantees no clashes.

module syntran_rt

    use, intrinsic :: iso_fortran_env, only: int32, int64, real32, real64, output_unit, &
        error_unit
    implicit none

    ! Arrays of strings are arrays of this, because Fortran has no array of
    ! varying-length strings
    type :: rt_str_t
        character(len = :), allocatable :: s
    end type rt_str_t

    ! Convert a scalar to a string exactly like syntran's println()/str() do.
    ! Note that the real kinds are *not* trimmed, for column alignment
    interface rt_str
        module procedure rt_str_bool, rt_str_i32, rt_str_i64, rt_str_f32, rt_str_f64, rt_str_str
    end interface rt_str

    ! Convert an array of rank 1 to 4 to a string, like rt_str() does for a scalar.
    ! These have explicit ranks and call the assumed-rank rt_str_a_<type> below,
    ! because gfortran mishandles an empty array *expression* that is passed
    ! straight to an assumed-rank dummy argument
    interface rt_str_a
        module procedure rt_str_a_bool_1, rt_str_a_bool_2, rt_str_a_bool_3, &
            rt_str_a_bool_4, rt_str_a_i32_1, rt_str_a_i32_2, rt_str_a_i32_3, &
            rt_str_a_i32_4, rt_str_a_i64_1, rt_str_a_i64_2, rt_str_a_i64_3, &
            rt_str_a_i64_4, rt_str_a_f32_1, rt_str_a_f32_2, rt_str_a_f32_3, &
            rt_str_a_f32_4, rt_str_a_f64_1, rt_str_a_f64_2, rt_str_a_f64_3, &
            rt_str_a_f64_4, rt_str_a_str_1, rt_str_a_str_2, rt_str_a_str_3, &
            rt_str_a_str_4
    end interface rt_str_a

    ! Convert an array that is a member of a struct to a string, which also
    ! writes how the type of its elements is given, like `[1'i64, 2'i64]`
    interface rt_str_a_rt
        module procedure rt_str_a_rt_i64, rt_str_a_rt_f32, rt_str_a_rt_str
    end interface rt_str_a_rt

    ! Whole-array equality of two arrays of the same rank, given as shapes and
    ! flattened elements: one bool, false if the shapes differ
    interface rt_arr_eq
        module procedure rt_arr_eq_bool, rt_arr_eq_i32, rt_arr_eq_i64, rt_arr_eq_f32, &
            rt_arr_eq_f64, rt_arr_eq_str
    end interface rt_arr_eq

contains

!===============================================================================

function rt_str_bool(x) result(s)
    logical, intent(in) :: x
    character(len = :), allocatable :: s
    if (x) then
        s = 'true'
    else
        s = 'false'
    end if
end function rt_str_bool

!===============================================================================

function rt_str_i32(x) result(s)
    integer(int32), intent(in) :: x
    character(len = :), allocatable :: s
    character(len = 16) :: buf
    write(buf, '(i0)') x
    s = trim(buf)
end function rt_str_i32

!===============================================================================

function rt_str_i64(x) result(s)
    integer(int64), intent(in) :: x
    character(len = :), allocatable :: s
    character(len = 24) :: buf
    write(buf, '(i0)') x
    s = trim(buf)
end function rt_str_i64

!===============================================================================

function rt_str_f32(x) result(s)
    real(real32), intent(in) :: x
    character(len = :), allocatable :: s
    character(len = 16) :: buf
    write(buf, '(es16.6)') x
    s = buf
end function rt_str_f32

!===============================================================================

function rt_str_f64(x) result(s)
    real(real64), intent(in) :: x
    character(len = :), allocatable :: s
    character(len = 28) :: buf
    write(buf, '(es25.15)') x
    s = buf
end function rt_str_f64

!===============================================================================

function rt_str_str(x) result(s)
    character(len = *), intent(in) :: x
    character(len = :), allocatable :: s
    s = x
end function rt_str_str

!===============================================================================

! Equality of two strings.  Fortran's `==` pads the shorter operand with blanks,
! so "a" == "a " would be true, unlike in syntran
pure function rt_str_eq(a, b) result(eq)
    character(len = *), intent(in) :: a, b
    logical :: eq
    eq = len(a) == len(b)
    if (eq) eq = a == b
end function rt_str_eq

!===============================================================================

! Length-aware lexicographic string less-than.  Fortran's `<` blank-pads the
! shorter operand first, so "a" < "a " would be false.  A string that is a
! strict prefix of another sorts first.  The other orderings derive from this:
!
!     a <= b  =  .not. rt_str_lt(b, a)
!     a >  b  =  rt_str_lt(b, a)
!     a >= b  =  .not. rt_str_lt(a, b)
pure function rt_str_lt(a, b) result(lt)
    character(len = *), intent(in) :: a, b
    logical :: lt
    integer :: i, n
    n = min(len(a), len(b))
    do i = 1, n
        if (a(i:i) /= b(i:i)) then
            lt = a(i:i) < b(i:i)
            return
        end if
    end do
    lt = len(a) < len(b)
end function rt_str_lt

!===============================================================================

! s[i], with a 0-based index.  This is for when the index is an expression which
! mustn't be evaluated twice
function rt_char_at(s, i) result(c)
    character(len = *), intent(in) :: s
    integer(int64), intent(in) :: i
    character(len = 1) :: c
    c = s(i + 1: i + 1)
end function rt_char_at

!===============================================================================

! println() writes each argument without advancing, then ends the line
subroutine rt_print(s)
    character(len = *), intent(in) :: s
    write(output_unit, '(a)', advance = 'no') s
end subroutine rt_print

!===============================================================================

subroutine rt_endl()
    write(output_unit, *)
end subroutine rt_endl

!===============================================================================

! exit() says so, then terminates the program with the given status
subroutine rt_exit(code)
    integer(int32), intent(in) :: code
    write(output_unit, *) 'Exiting syntran with status '//rt_str_i32(code)
    stop code, quiet = .true.
end subroutine rt_exit

!===============================================================================

! The CLI prints the value of the program's last statement after it finishes,
! indented with 4 spaces (and a 5th from list-directed output)
subroutine rt_result(s)
    character(len = *), intent(in) :: s
    write(output_unit, *) '    '//s
end subroutine rt_result

!===============================================================================

! A runtime error is fatal.  Compile with -fcheck=all to also catch subscripts
! which are out of bounds
subroutine rt_fatal(msg)
    character(len = *), intent(in) :: msg
    write(error_unit, '(a)') 'Runtime error: '//msg
    error stop 1
end subroutine rt_fatal

!===============================================================================

! Arrays of strings are built element by element.  Fortran's spread() and
! reshape() copy an array of a type with an allocatable component shallowly, so
! the strings of the result would dangle once the argument is freed

function rt_fill_str(s, n) result(r)
    character(len = *), intent(in) :: s
    integer(int64), intent(in) :: n
    type(rt_str_t), allocatable :: r(:)
    integer(int64) :: i
    allocate(r(max(0_int64, n)))
    do i = 1, n
        r(i)%s = s
    end do
end function rt_fill_str

function rt_reshape_str_2(a, n1, n2) result(r)
    type(rt_str_t), intent(in) :: a(:)
    integer(int64), intent(in) :: n1, n2
    type(rt_str_t), allocatable :: r(:,:)
    integer(int64) :: i, j, k
    if (n1 * n2 /= size(a)) call rt_fatal('array size does not match its shape')
    allocate(r(n1, n2))
    k = 0
    do j = 1, n2
        do i = 1, n1
            k = k + 1
            r(i, j)%s = a(k)%s
        end do
    end do
end function rt_reshape_str_2

function rt_reshape_str_3(a, n1, n2, n3) result(r)
    type(rt_str_t), intent(in) :: a(:)
    integer(int64), intent(in) :: n1, n2, n3
    type(rt_str_t), allocatable :: r(:,:,:)
    integer(int64) :: i, j, l, k
    if (n1 * n2 * n3 /= size(a)) call rt_fatal('array size does not match its shape')
    allocate(r(n1, n2, n3))
    k = 0
    do l = 1, n3
        do j = 1, n2
            do i = 1, n1
                k = k + 1
                r(i, j, l)%s = a(k)%s
            end do
        end do
    end do
end function rt_reshape_str_3

function rt_reshape_str_4(a, n1, n2, n3, n4) result(r)
    type(rt_str_t), intent(in) :: a(:)
    integer(int64), intent(in) :: n1, n2, n3, n4
    type(rt_str_t), allocatable :: r(:,:,:,:)
    integer(int64) :: i, j, l, m, k
    if (n1 * n2 * n3 * n4 /= size(a)) call rt_fatal('array size does not match its shape')
    allocate(r(n1, n2, n3, n4))
    k = 0
    do m = 1, n4
        do l = 1, n3
            do j = 1, n2
                do i = 1, n1
                    k = k + 1
                    r(i, j, l, m)%s = a(k)%s
                end do
            end do
        end do
    end do
end function rt_reshape_str_4

!===============================================================================

! Convert a string to a number, like the interpreter's parse_*() fns do.  A
! string which isn't a number is a fatal error

function rt_parse_i32(s) result(r)
    character(len = *), intent(in) :: s
    integer(int32) :: r
    integer :: io
    read(s, *, iostat = io) r
    if (io /= 0) call rt_fatal(' cannot parse_i32() for argument `'//s//'`')
end function rt_parse_i32

function rt_parse_i64(s) result(r)
    character(len = *), intent(in) :: s
    integer(int64) :: r
    integer :: io
    read(s, *, iostat = io) r
    if (io /= 0) call rt_fatal(' cannot parse_i64() for argument `'//s//'`')
end function rt_parse_i64

function rt_parse_f32(s) result(r)
    character(len = *), intent(in) :: s
    real(real32) :: r
    integer :: io
    read(s, *, iostat = io) r
    if (io /= 0) call rt_fatal(' cannot parse_f32() for argument `'//s//'`')
end function rt_parse_f32

function rt_parse_f64(s) result(r)
    character(len = *), intent(in) :: s
    real(real64) :: r
    integer :: io
    read(s, *, iostat = io) r
    if (io /= 0) call rt_fatal(' cannot parse_f64() for argument `'//s//'`')
end function rt_parse_f64

!===============================================================================

! The array [lb: ub], which is empty if ub <= lb
function rt_range_i32(lb, ub) result(r)
    integer(int32), intent(in) :: lb, ub
    integer(int32), allocatable :: r(:)
    integer(int32) :: i
    r = [(i, i = lb, ub - 1_int32)]
end function rt_range_i32

function rt_range_i64(lb, ub) result(r)
    integer(int64), intent(in) :: lb, ub
    integer(int64), allocatable :: r(:)
    integer(int64) :: i
    r = [(i, i = lb, ub - 1_int64)]
end function rt_range_i64

!===============================================================================

! The array [lb: step: ub].  The bound is exclusive and the step may be
! negative.  This is the same algorithm as the interpreter's, including its
! "(i < ub) .eqv. (lb < ub)" loop condition, so that results are identical

function rt_step_i32(lb, step, ub) result(r)
    integer(int32), intent(in) :: lb, step, ub
    integer(int32), allocatable :: r(:)
    integer(int32) :: i
    integer :: j, cap
    if (step == 0) call rt_fatal('array step is 0')
    cap = max(0, (ub - lb + step - sign(1_int32, step)) / step)
    allocate(r(cap))
    j = 1
    i = lb
    if ((lb < ub) .neqv. (0 < step)) i = ub
    do while (((i < ub) .eqv. (lb < ub)) .and. i /= ub)
        r(j) = i
        i = i + step
        j = j + 1
    end do
    r = r(1: j - 1)
end function rt_step_i32

function rt_step_i64(lb, step, ub) result(r)
    integer(int64), intent(in) :: lb, step, ub
    integer(int64), allocatable :: r(:)
    integer(int64) :: i
    integer :: j, cap
    if (step == 0) call rt_fatal('array step is 0')
    cap = int(max(0_int64, (ub - lb + step - sign(1_int64, step)) / step))
    allocate(r(cap))
    j = 1
    i = lb
    if ((lb < ub) .neqv. (0 < step)) i = ub
    do while (((i < ub) .eqv. (lb < ub)) .and. i /= ub)
        r(j) = i
        i = i + step
        j = j + 1
    end do
    r = r(1: j - 1)
end function rt_step_i64

function rt_step_f32(lb, step, ub) result(r)
    real(real32), intent(in) :: lb, step, ub
    real(real32), allocatable :: r(:)
    real(real32) :: f
    integer :: j, cap
    if (.not. (step > 0.0_real32 .or. step < 0.0_real32)) call rt_fatal('array step is 0.0')
    cap = max(0, ceiling((ub - lb) / step))
    allocate(r(cap))
    j = 1
    f = lb
    if ((lb < ub) .neqv. (0 < step)) f = ub
    do while (((f < ub) .eqv. (lb < ub)) .and. (f < ub .or. f > ub))
        r(j) = f
        ! Multiplying instead of repeatedly adding keeps rounding errors from
        ! accumulating, e.g. [0.0: 0.1: 0.9]
        f = lb + j * step
        j = j + 1
    end do
    r = r(1: j - 1)
end function rt_step_f32

function rt_step_f64(lb, step, ub) result(r)
    real(real64), intent(in) :: lb, step, ub
    real(real64), allocatable :: r(:)
    real(real64) :: f
    integer :: j, cap
    if (.not. (step > 0.0_real64 .or. step < 0.0_real64)) call rt_fatal('array step is 0.0')
    cap = max(0, ceiling((ub - lb) / step))
    allocate(r(cap))
    j = 1
    f = lb
    if ((lb < ub) .neqv. (0 < step)) f = ub
    do while (((f < ub) .eqv. (lb < ub)) .and. (f < ub .or. f > ub))
        r(j) = f
        f = lb + j * step
        j = j + 1
    end do
    r = r(1: j - 1)
end function rt_step_f64

!===============================================================================

! The array [lb: ub; n] of n evenly spaced values, including both ends

function rt_linspace_f32(lb, ub, n) result(r)
    real(real32), intent(in) :: lb, ub
    integer(int64), intent(in) :: n
    real(real32), allocatable :: r(:)
    real(real32) :: dx
    integer :: i
    allocate(r(max(0_int64, n)))
    dx = (ub - lb) / real(n - 1)
    do i = 0, int(n) - 1
        r(i + 1) = lb + i * dx
    end do
end function rt_linspace_f32

function rt_linspace_f64(lb, ub, n) result(r)
    real(real64), intent(in) :: lb, ub
    integer(int64), intent(in) :: n
    real(real64), allocatable :: r(:)
    real(real64) :: dx
    integer :: i
    allocate(r(max(0_int64, n)))
    dx = (ub - lb) / real(n - 1, real64)
    do i = 0, int(n) - 1
        r(i + 1) = lb + i * dx
    end do
end function rt_linspace_f64

!===============================================================================

! Join the already-formatted elements of an array of shape `shp`, which are in
! storage (column-major) order.  Elements are separated by ", ".  A rank > 1
! array starts and ends with a line break, and also has one after every
! complete row (and plane, etc.), exactly like the interpreter prints them
function rt_join(items, shp) result(s)
    type(rt_str_t), intent(in) :: items(:)
    integer, intent(in) :: shp(:)
    character(len = :), allocatable :: s

    character(len = :), allocatable :: buf
    integer :: i, j, n, pos, prod, need
    character, parameter :: lf = achar(10)

    n = size(items)
    allocate(character(len = 64) :: buf)
    pos = 0

    call put('[')
    if (size(shp) > 1) call put(lf)

    do i = 1, n
        call put(items(i)%s)
        if (i >= n) cycle
        call put(', ')

        prod = shp(1)
        do j = 2, size(shp)
            if (mod(i, prod) == 0) call put(lf)
            prod = prod * shp(j)
        end do
    end do

    if (size(shp) > 1) call put(lf)
    call put(']')

    s = buf(1: pos)

contains

    ! Append to the buffer, doubling its capacity as needed
    subroutine put(str)
        character(len = *), intent(in) :: str
        character(len = :), allocatable :: tmp
        need = pos + len(str)
        if (need > len(buf)) then
            allocate(character(len = max(need, 2 * len(buf))) :: tmp)
            tmp(1: pos) = buf(1: pos)
            call move_alloc(tmp, buf)
        end if
        buf(pos + 1: need) = str
        pos = need
    end subroutine put

end function rt_join

!===============================================================================

function rt_str_a_bool(x) result(s)
    logical, intent(in) :: x(..)
    character(len = :), allocatable :: s
    select rank (x)
    rank (1)
        s = rt_join(items(x), shape(x))
    rank (2)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (3)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (4)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank default
        call rt_fatal('arrays of rank > 4 are not supported by rt_str_a()')
    end select
contains
    function items(a) result(r)
        logical, intent(in) :: a(:)
        type(rt_str_t), allocatable :: r(:)
        integer :: i
        allocate(r(size(a)))
        do i = 1, size(a)
            r(i)%s = rt_str_bool(a(i))
        end do
    end function items
end function rt_str_a_bool

function rt_str_a_i32(x) result(s)
    integer(int32), intent(in) :: x(..)
    character(len = :), allocatable :: s
    select rank (x)
    rank (1)
        s = rt_join(items(x), shape(x))
    rank (2)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (3)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (4)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank default
        call rt_fatal('arrays of rank > 4 are not supported by rt_str_a()')
    end select
contains
    function items(a) result(r)
        integer(int32), intent(in) :: a(:)
        type(rt_str_t), allocatable :: r(:)
        integer :: i
        allocate(r(size(a)))
        do i = 1, size(a)
            r(i)%s = rt_str_i32(a(i))
        end do
    end function items
end function rt_str_a_i32

function rt_str_a_i64(x) result(s)
    integer(int64), intent(in) :: x(..)
    character(len = :), allocatable :: s
    select rank (x)
    rank (1)
        s = rt_join(items(x), shape(x))
    rank (2)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (3)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (4)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank default
        call rt_fatal('arrays of rank > 4 are not supported by rt_str_a()')
    end select
contains
    function items(a) result(r)
        integer(int64), intent(in) :: a(:)
        type(rt_str_t), allocatable :: r(:)
        integer :: i
        allocate(r(size(a)))
        do i = 1, size(a)
            r(i)%s = rt_str_i64(a(i))
        end do
    end function items
end function rt_str_a_i64

! The elements of a real array are trimmed, unlike a scalar's
function rt_str_a_f32(x) result(s)
    real(real32), intent(in) :: x(..)
    character(len = :), allocatable :: s
    select rank (x)
    rank (1)
        s = rt_join(items(x), shape(x))
    rank (2)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (3)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (4)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank default
        call rt_fatal('arrays of rank > 4 are not supported by rt_str_a()')
    end select
contains
    function items(a) result(r)
        real(real32), intent(in) :: a(:)
        type(rt_str_t), allocatable :: r(:)
        integer :: i
        allocate(r(size(a)))
        do i = 1, size(a)
            r(i)%s = trim(adjustl(rt_str_f32(a(i))))
        end do
    end function items
end function rt_str_a_f32

function rt_str_a_f64(x) result(s)
    real(real64), intent(in) :: x(..)
    character(len = :), allocatable :: s
    select rank (x)
    rank (1)
        s = rt_join(items(x), shape(x))
    rank (2)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (3)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (4)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank default
        call rt_fatal('arrays of rank > 4 are not supported by rt_str_a()')
    end select
contains
    function items(a) result(r)
        real(real64), intent(in) :: a(:)
        type(rt_str_t), allocatable :: r(:)
        integer :: i
        allocate(r(size(a)))
        do i = 1, size(a)
            r(i)%s = trim(adjustl(rt_str_f64(a(i))))
        end do
    end function items
end function rt_str_a_f64

function rt_str_a_str(x) result(s)
    type(rt_str_t), intent(in) :: x(..)
    character(len = :), allocatable :: s
    select rank (x)
    rank (1)
        s = rt_join(x, shape(x))
    rank (2)
        s = rt_join(reshape(x, [size(x)]), shape(x))
    rank (3)
        s = rt_join(reshape(x, [size(x)]), shape(x))
    rank (4)
        s = rt_join(reshape(x, [size(x)]), shape(x))
    rank default
        call rt_fatal('arrays of rank > 4 are not supported by rt_str_a()')
    end select
end function rt_str_a_str

!===============================================================================

function rt_str_a_bool_1(x) result(s)
    logical, intent(in) :: x(:)
    character(len = :), allocatable :: s
    s = rt_str_a_bool(x)
end function rt_str_a_bool_1

function rt_str_a_bool_2(x) result(s)
    logical, intent(in) :: x(:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_bool(x)
end function rt_str_a_bool_2

function rt_str_a_bool_3(x) result(s)
    logical, intent(in) :: x(:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_bool(x)
end function rt_str_a_bool_3

function rt_str_a_bool_4(x) result(s)
    logical, intent(in) :: x(:,:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_bool(x)
end function rt_str_a_bool_4

function rt_str_a_i32_1(x) result(s)
    integer(int32), intent(in) :: x(:)
    character(len = :), allocatable :: s
    s = rt_str_a_i32(x)
end function rt_str_a_i32_1

function rt_str_a_i32_2(x) result(s)
    integer(int32), intent(in) :: x(:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_i32(x)
end function rt_str_a_i32_2

function rt_str_a_i32_3(x) result(s)
    integer(int32), intent(in) :: x(:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_i32(x)
end function rt_str_a_i32_3

function rt_str_a_i32_4(x) result(s)
    integer(int32), intent(in) :: x(:,:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_i32(x)
end function rt_str_a_i32_4

function rt_str_a_i64_1(x) result(s)
    integer(int64), intent(in) :: x(:)
    character(len = :), allocatable :: s
    s = rt_str_a_i64(x)
end function rt_str_a_i64_1

function rt_str_a_i64_2(x) result(s)
    integer(int64), intent(in) :: x(:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_i64(x)
end function rt_str_a_i64_2

function rt_str_a_i64_3(x) result(s)
    integer(int64), intent(in) :: x(:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_i64(x)
end function rt_str_a_i64_3

function rt_str_a_i64_4(x) result(s)
    integer(int64), intent(in) :: x(:,:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_i64(x)
end function rt_str_a_i64_4

function rt_str_a_f32_1(x) result(s)
    real(real32), intent(in) :: x(:)
    character(len = :), allocatable :: s
    s = rt_str_a_f32(x)
end function rt_str_a_f32_1

function rt_str_a_f32_2(x) result(s)
    real(real32), intent(in) :: x(:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_f32(x)
end function rt_str_a_f32_2

function rt_str_a_f32_3(x) result(s)
    real(real32), intent(in) :: x(:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_f32(x)
end function rt_str_a_f32_3

function rt_str_a_f32_4(x) result(s)
    real(real32), intent(in) :: x(:,:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_f32(x)
end function rt_str_a_f32_4

function rt_str_a_f64_1(x) result(s)
    real(real64), intent(in) :: x(:)
    character(len = :), allocatable :: s
    s = rt_str_a_f64(x)
end function rt_str_a_f64_1

function rt_str_a_f64_2(x) result(s)
    real(real64), intent(in) :: x(:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_f64(x)
end function rt_str_a_f64_2

function rt_str_a_f64_3(x) result(s)
    real(real64), intent(in) :: x(:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_f64(x)
end function rt_str_a_f64_3

function rt_str_a_f64_4(x) result(s)
    real(real64), intent(in) :: x(:,:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_f64(x)
end function rt_str_a_f64_4

function rt_str_a_str_1(x) result(s)
    type(rt_str_t), intent(in) :: x(:)
    character(len = :), allocatable :: s
    s = rt_str_a_str(x)
end function rt_str_a_str_1

function rt_str_a_str_2(x) result(s)
    type(rt_str_t), intent(in) :: x(:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_str(x)
end function rt_str_a_str_2

function rt_str_a_str_3(x) result(s)
    type(rt_str_t), intent(in) :: x(:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_str(x)
end function rt_str_a_str_3

function rt_str_a_str_4(x) result(s)
    type(rt_str_t), intent(in) :: x(:,:,:,:)
    character(len = :), allocatable :: s
    s = rt_str_a_str(x)
end function rt_str_a_str_4

!===============================================================================

! Elemental versions of the operators that Fortran doesn't have for the
! strings in an array of rt_str_t

elemental function rt_cat(a, b) result(r)
    type(rt_str_t), intent(in) :: a, b
    type(rt_str_t) :: r
    r%s = a%s // b%s
end function rt_cat

elemental function rt_eq(a, b) result(r)
    type(rt_str_t), intent(in) :: a, b
    logical :: r
    r = rt_str_eq(a%s, b%s)
end function rt_eq

elemental function rt_lt(a, b) result(r)
    type(rt_str_t), intent(in) :: a, b
    logical :: r
    r = rt_str_lt(a%s, b%s)
end function rt_lt

elemental function rt_str_t_of(s) result(r)
    character(len = *), intent(in) :: s
    type(rt_str_t) :: r
    r%s = s
end function rt_str_t_of

!===============================================================================

function rt_str_a_rt_i64(x) result(s)
    integer(int64), intent(in) :: x(..)
    character(len = :), allocatable :: s
    select rank (x)
    rank (1)
        s = rt_join(items(x), shape(x))
    rank (2)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (3)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (4)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank default
        call rt_fatal('arrays of rank > 4 are not supported by rt_str_a_rt()')
    end select
contains
    function items(a) result(r)
        integer(int64), intent(in) :: a(:)
        type(rt_str_t), allocatable :: r(:)
        integer :: i
        allocate(r(size(a)))
        do i = 1, size(a)
            r(i)%s = rt_str_i64(a(i)) // "'i64"
        end do
    end function items
end function rt_str_a_rt_i64

function rt_str_a_rt_f32(x) result(s)
    real(real32), intent(in) :: x(..)
    character(len = :), allocatable :: s
    select rank (x)
    rank (1)
        s = rt_join(items(x), shape(x))
    rank (2)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (3)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (4)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank default
        call rt_fatal('arrays of rank > 4 are not supported by rt_str_a_rt()')
    end select
contains
    function items(a) result(r)
        real(real32), intent(in) :: a(:)
        type(rt_str_t), allocatable :: r(:)
        integer :: i
        allocate(r(size(a)))
        do i = 1, size(a)
            r(i)%s = trim(adjustl(rt_str_f32(a(i)))) // "'f32"
        end do
    end function items
end function rt_str_a_rt_f32

function rt_str_a_rt_str(x) result(s)
    type(rt_str_t), intent(in) :: x(..)
    character(len = :), allocatable :: s
    select rank (x)
    rank (1)
        s = rt_join(items(x), shape(x))
    rank (2)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (3)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank (4)
        s = rt_join(items(reshape(x, [size(x)])), shape(x))
    rank default
        call rt_fatal('arrays of rank > 4 are not supported by rt_str_a_rt()')
    end select
contains
    function items(a) result(r)
        type(rt_str_t), intent(in) :: a(:)
        type(rt_str_t), allocatable :: r(:)
        integer :: i
        allocate(r(size(a)))
        do i = 1, size(a)
            r(i)%s = rt_quote(a(i)%s)
        end do
    end function items
end function rt_str_a_rt_str

!===============================================================================

! A string as a struct prints it, in double quotes with any quote doubled

function rt_quote(s) result(r)
    character(len = *), intent(in) :: s
    character(len = :), allocatable :: r
    integer :: i
    r = '"'
    do i = 1, len(s)
        if (s(i:i) == '"') r = r // '"'
        r = r // s(i:i)
    end do
    r = r // '"'
end function rt_quote

!===============================================================================

! The elements of an array of structs, which are already joined, in brackets.
! An array of rank > 1 has a line feed after the opening and before the closing
! bracket, but not between its rows

function rt_arr_wrap(joined, rank_) result(r)
    character(len = *), intent(in) :: joined
    integer, intent(in) :: rank_
    character(len = :), allocatable :: r
    if (rank_ > 1) then
        r = '[' // new_line('a') // joined // new_line('a') // ']'
    else
        r = '[' // joined // ']'
    end if
end function rt_arr_wrap

!===============================================================================

! Whole-array equality, for the match of a `switch` on an array.  Unlike the
! elementwise `==` it is a single bool, and arrays of different shapes are just
! not equal.  Each array is passed as its shape and its elements flattened to
! rank 1, like `rt_arr_eq(shape(a), reshape(a, [size(a)]), shape(b), ...)`.  That
! is for any rank, and it avoids an assumed-rank dummy argument, which gfortran
! gets wrong for an empty array expression

function rt_arr_eq_bool(sa, va, sb, vb) result(r)
    integer, intent(in) :: sa(:), sb(:)
    logical, intent(in) :: va(:), vb(:)
    logical :: r
    r = .false.
    if (size(sa) /= size(sb)) return
    if (any(sa /= sb)) return
    r = all(va .eqv. vb)
end function rt_arr_eq_bool

function rt_arr_eq_i32(sa, va, sb, vb) result(r)
    integer, intent(in) :: sa(:), sb(:)
    integer(int32), intent(in) :: va(:), vb(:)
    logical :: r
    r = .false.
    if (size(sa) /= size(sb)) return
    if (any(sa /= sb)) return
    r = all(va == vb)
end function rt_arr_eq_i32

function rt_arr_eq_i64(sa, va, sb, vb) result(r)
    integer, intent(in) :: sa(:), sb(:)
    integer(int64), intent(in) :: va(:), vb(:)
    logical :: r
    r = .false.
    if (size(sa) /= size(sb)) return
    if (any(sa /= sb)) return
    r = all(va == vb)
end function rt_arr_eq_i64

function rt_arr_eq_f32(sa, va, sb, vb) result(r)
    integer, intent(in) :: sa(:), sb(:)
    real(real32), intent(in) :: va(:), vb(:)
    logical :: r
    r = .false.
    if (size(sa) /= size(sb)) return
    if (any(sa /= sb)) return
    r = all(va == vb)
end function rt_arr_eq_f32

function rt_arr_eq_f64(sa, va, sb, vb) result(r)
    integer, intent(in) :: sa(:), sb(:)
    real(real64), intent(in) :: va(:), vb(:)
    logical :: r
    r = .false.
    if (size(sa) /= size(sb)) return
    if (any(sa /= sb)) return
    r = all(va == vb)
end function rt_arr_eq_f64

function rt_arr_eq_str(sa, va, sb, vb) result(r)
    integer, intent(in) :: sa(:), sb(:)
    type(rt_str_t), intent(in) :: va(:), vb(:)
    logical :: r
    r = .false.
    if (size(sa) /= size(sb)) return
    if (any(sa /= sb)) return
    r = all(rt_eq(va, vb))
end function rt_arr_eq_str

!===============================================================================

end module syntran_rt

!===============================================================================

