#!/usr/bin/env bash

set -eu

# Embed src/rt/syntran_rt.f90 into src/transpile_rt.f90 as a table of string
# literals, so the transpiler can emit the runtime module at the top of every
# generated program without reading any file at run time.
#
# Run this after editing src/rt/syntran_rt.f90.  CI re-runs it and fails if the
# checked-in src/transpile_rt.f90 differs.
#
# Usage (from anywhere):
#
#     bash src/gen_transpile_rt.sh

src_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
in="$src_dir/rt/syntran_rt.f90"
out="$src_dir/transpile_rt.f90"

# gfortran's default free-form line limit is 132 chars.  The generated
# `call v%push('...')` wrapper adds 16 chars and each quote may be doubled
maxlen=100
bad=$(awk -v max=$maxlen 'length($0) > max { print FILENAME ":" NR ": " length($0) " chars" }' "$in")
if [ -n "$bad" ]; then
	echo "error: lines longer than $maxlen chars:" >&2
	echo "$bad" >&2
	exit 1
fi

if grep -q $'\t' "$in"; then
	echo "error: $in contains tab characters" >&2
	exit 1
fi

{
	cat <<'EOF'

!===============================================================================

! GENERATED by src/gen_transpile_rt.sh from src/rt/syntran_rt.f90.  Do not edit
! by hand: edit the runtime source and re-run the script

module syntran__transpile_rt_m

	use syntran__utils_m

	implicit none

contains

!===============================================================================

function transpile_rt_src() result(v)

	! Source lines of the runtime module embedded in every transpiled program

	type(string_vector_t) :: v

	v = new_string_vector()
EOF

	# Strip trailing whitespace, double any single quotes, wrap in a push call
	sed -e 's/[[:space:]]*$//' -e "s/'/''/g" -e "s/^\(.*\)\$/\tcall v%push('\1')/" "$in"

	cat <<'EOF'

end function transpile_rt_src

!===============================================================================

end module syntran__transpile_rt_m

!===============================================================================

EOF
} > "$out"

echo "wrote $out"
