
name: CI

on: [push]

#defaults:
#  run:
#    shell: bash

jobs:
  test:

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        #os: [ubuntu-latest, macOS-latest]
        #os: [ubuntu-latest, windows-latest]
        #os: [ubuntu-latest]

    steps:

    - uses: actions/checkout@v1

    - uses: fortran-lang/setup-fpm@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - if: matrix.os == 'ubuntu-latest'
      name: Test ubuntu fpm default
      run: |
        fpm test

    - if: matrix.os == 'ubuntu-latest'
      name: Test ubuntu gfortran-11
      env:
        FPM_FC=gfortran-11
      run: |
        fpm test

    - if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install gfortran
    - if: matrix.os == 'macOS-latest'
      run: |
        brew install gcc@12
        brew reinstall gcc@12

    #- name: Checkout submodules
    #  shell: bash
    #  run: |
    #    git submodule update --init --recursive || echo "ignoring submodule error"
    - name: Build
      run: |
        #export OMP_NUM_THREADS=1
        bash ./build.sh debug
        #ls -ltrh build/

    - if: matrix.os != 'windows-latest'
      name: Test debug
      run: |
        ./build/syntran < samples/arithmetic.syntran
        #./build/syntran < samples/bad-syntax.syntran
        time ./build/test

    - if: matrix.os != 'windows-latest'
      name: Test release
      run: |
        bash ./build.sh release
        time ./build/test

    #- if: matrix.os == 'windows-latest'
    #  shell: bash
    #  run: |
    #    which gfortran
    #    #where gfortran
    #    #set PATH
    #    #echo %PATH%
    #    echo "PATH = "
    #    echo $PATH
    #    echo "GITHUB_PATH = "
    #    echo $GITHUB_PATH
    #    #Get-Content samples/arithmetic.syntran | ./build/syntran
    #    ./build/test.exe

