
name: CI

on: [push]

#defaults:
#  run:
#    shell: bash

jobs:

  test-os:

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:

      # Having multiple matrices (e.g. os *and* gfortran) will test every
      # possible combination of those two matrices!
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        #os: [ubuntu-latest, macOS-latest]
        #os: [ubuntu-latest, windows-latest]
        #os: [ubuntu-latest]
        #gfortran: [11, 12]

    steps:

    - uses: actions/checkout@v1
    - uses: fortran-lang/setup-fpm@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - if: matrix.os == 'ubuntu-latest'
      name: Set ubuntu PATH
      run: |
        echo "$HOME/bin" >> $GITHUB_PATH

    - if: matrix.os == 'ubuntu-latest'
      name: Test fpm default
      env:
        #FPM_FC: gfortran-${{ matrix.gfortran }}
        FPM_FC: gfortran-12
      run: |
        fpm install --prefix='$HOME'
        which syntran
        chmod +x ./samples/shebang.syntran
        ./samples/shebang.syntran
        fpm test test
        fpm test long

    - if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install gfortran

    - if: matrix.os == 'macOS-latest'
      run: |
        brew install gcc@12
        brew reinstall gcc@12

    #- name: Checkout submodules
    #  shell: bash
    #  run: |
    #    git submodule update --init --recursive || echo "ignoring submodule error"
    - name: Build
      run: |
        #export OMP_NUM_THREADS=1
        bash ./build.sh debug
        #ls -ltrh build/

    - if: matrix.os != 'windows-latest'
      name: Test debug
      run: |
        ./build/syntran < samples/arithmetic.syntran
        #./build/syntran < samples/bad-syntax.syntran
        time ./build/test

    - if: matrix.os != 'windows-latest'
      name: Test release
      run: |
        bash ./build.sh release
        time ./build/test

    #- if: matrix.os == 'windows-latest'
    #  shell: bash
    #  run: |
    #    which gfortran
    #    #where gfortran
    #    #set PATH
    #    #echo %PATH%
    #    echo "PATH = "
    #    echo $PATH
    #    echo "GITHUB_PATH = "
    #    echo $GITHUB_PATH
    #    #Get-Content samples/arithmetic.syntran | ./build/syntran
    #    ./build/test.exe

  test-gfortran:

    name: Test with gfortran-${{ matrix.gfortran }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macOS-latest]
        #os: [ubuntu-latest, macOS-latest]
        #os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        #gfortran: [10, 11, 12, 13]  # TODO: gfort 13 has an issue
        gfortran: [9, 10, 11, 12]  # gfort <= 8 not available by default on github ci workers

    steps:

    - uses: actions/checkout@v1
    - uses: fortran-lang/setup-fpm@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - if: matrix.os == 'ubuntu-latest'
      name: Test ubuntu gfortran-${{ matrix.gfortran }}
      env:
        FPM_FC: gfortran-${{ matrix.gfortran }}
      run: |
        fpm test test --verbose --flag -Wno-tabs
        fpm test long

